Add check against PRs from forked repositories

diff --git a/.github/workflows/backport.yml b/.github/workflows/backport.yml
--- a/.github/workflows/backport.yml
+++ b/.github/workflows/backport.yml
@@ -12,10 +12,12 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
-    - name: Check preconditions
+    - name: Check repository
       run: |
-        echo "Validating"
-        exit 1
+        if [ "${{ github.event.pull_request.base.repo.html_url }}" != "${{ github.event.pull_request.head.repo.html_url }}" ]; then
+          echo "ERROR: Cross-repository pull requests, e.g. from forks, are not supported."
+          exit 1
+        fi
     - name: Create pull request
       uses: repo-sync/pull-request@v2.0.1
       with:
